// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: jobs.sql

package repo

import (
	"context"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (name, priority, state)
VALUES (?, ?, ?)
RETURNING id, name, priority, state, created_at, edited_at
`

type CreateJobParams struct {
	Name     string `json:"name"`
	Priority int64  `json:"priority"`
	State    string `json:"state"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob, arg.Name, arg.Priority, arg.State)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.State,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const getJobs = `-- name: GetJobs :many
SELECT id, name, priority, state, created_at, edited_at FROM jobs
`

func (q *Queries) GetJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, getJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Priority,
			&i.State,
			&i.CreatedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
