// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"time"
)

type Job struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Priority  int64     `json:"priority"`
	State     string    `json:"state"`
	CreatedAt time.Time `json:"created_at"`
	EditedAt  time.Time `json:"edited_at"`
}

type Task struct {
	ID        int64     `json:"id"`
	Priority  int64     `json:"priority"`
	Data      string    `json:"data"`
	State     string    `json:"state"`
	CreatedAt time.Time `json:"created_at"`
	EditedAt  time.Time `json:"edited_at"`
	JobID     int64     `json:"job_id"`
}

type Worker struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	State     string    `json:"state"`
	Metadata  string    `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
	EditedAt  time.Time `json:"edited_at"`
	TaskID    *int64    `json:"task_id"`
}
